version: "3.8"
services:
  database-productos:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: upsa
      POSTGRES_USER: system
      POSTGRES_PASSWORD: manager
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume_productos:/var/lib/postgresql/data/pgdata


  database-socios:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: upsa
      POSTGRES_USER: system
      POSTGRES_PASSWORD: manager
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
          - volume_socios:/var/lib/postgresql/data/pgdata



  redis-master-socio:
    image: bitnami/redis
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PORT_NUMBER: 6379
      REDIS_PASSWORD: masterpassword
    expose:
      - 6379

  redis-slave-socio:
    image: bitnami/redis
    deploy:
      replicas: 3
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master-socio
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_PASSWORD: masterpassword
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
    expose:
      - 6379
    depends_on:
      - redis-master-socio

  redis-master-producto:
    image: bitnami/redis
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PORT_NUMBER: 6379
      REDIS_PASSWORD: masterpassword
    expose:
      - 6379

  redis-slave-producto:
    image: bitnami/redis
    deploy:
      replicas: 3
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master-producto
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_PASSWORD: masterpassword
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
    expose:
      - 6379
    depends_on:
      - redis-master-producto


  socios:
    image: enriqueav99/ws-socios
    ports:
      - 9091:8081
    environment:
      QUARKUS_REDIS_HOSTS: redis://redis-master-socio:6379
      QUARKUS_REDIS_CLIENT_TYPE: replication
      QUARKUS_REDIS_PASSWORD: masterpassword

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database-socios:5432/upsa

      QUARKUS_FLYWAY_CLEAN_AT_START: true
      QUARKUS_FLYWAY_MIGRATE_AT_START: true

      QUARKUS_SWAGGER_UI_ENABLE: true
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    depends_on:
      - database-socios
      - redis-master-socio

  productos:
    image: enriqueav99/ws-productos
    ports:
      - 9092:8082
    environment:
      QUARKUS_REDIS_HOSTS: redis://redis-master-producto:6379
      QUARKUS_REDIS_CLIENT_TYPE: replication
      QUARKUS_REDIS_PASSWORD: masterpassword

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database-productos:5432/upsa

      QUARKUS_FLYWAY_CLEAN_AT_START: true
      QUARKUS_FLYWAY_MIGRATE_AT_START: true

      QUARKUS_SWAGGER_UI_ENABLE: true
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    depends_on:
      - database-productos
      - redis-master-producto


  gateway:
    image: enriqueav99/gateway
    ports:
      - 9999:8888
    environment:
      SOCIOS_API_MP_REST_URI: http://socios:8081
      PRODUCTOS_API_MP_REST_URI: http://productos:8082
    depends_on:
      - productos
      - socios

volumes:
   volume_socios: {}
   volume_productos: {}