version: "3.8"
services:
  database:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: upsa
      POSTGRES_USER: system
      POSTGRES_PASSWORD: manager
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume_database:/var/lib/postgresql/data/pgdata

  redis-1:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379

  redis-2:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379

  redis-3:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379

  redis-4:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379

  redis-5:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379

  redis-6:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6 redis-7
    expose:
      - 6379



  redis-7:
    image: bitnami/redis-cluster
    environment:
      REDIS_PORT_NUMBER: 6379
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_CLUSTER_CREATOR: yes
      REDIS_NODES: redis-1 redis-2 redis-3 redis-4 redis-5 redis-6
    expose:
      - 6379
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

  quarkus-1:
    build:
      dockerfile: Dockerfile
    ports:
      - 9091:8081
    environment:
      QUARKUS_REDIS_HOSTS: redis://redis-1:6379,redis://redis-2:6379,redis://redis-3:6379,redis://redis-4:6379,redis://redis-5:6379,redis://redis-6:6379,redis://redis-7:6379
      QUARKUS_REDIS_CLIENT_TYPE: cluster
      QUARKUS_REDIS_REPLICAS: share

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/upsa

      QUARKUS_FLYWAY_CLEAN_AT_START: true
      QUARKUS_FLYWAY_MIGRATE_AT_START: true

      QUARKUS_SWAGGER_UI_ENABLE: true
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    depends_on:
      - database
      - redis
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
      - redis-7

  quarkus-2:
    build:
      dockerfile: Dockerfile
    ports:
      - 9191:8081
    environment:
      QUARKUS_REDIS_HOSTS: redis://redis-1:6379,redis://redis-2:6379,redis://redis-3:6379,redis://redis-4:6379,redis://redis-5:6379,redis://redis-6:6379,redis://redis-7:6379
      QUARKUS_REDIS_CLIENT_TYPE: cluster
      QUARKUS_REDIS_REPLICAS: share

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/upsa

      QUARKUS_FLYWAY_CLEAN_AT_START: true
      QUARKUS_FLYWAY_MIGRATE_AT_START: true

      QUARKUS_SWAGGER_UI_ENABLE: true
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    depends_on:
      - database
      - redis
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
      - redis-7

volumes:
  volume_database: {}
