version: "3.8"
services:
  database:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: upsa
      POSTGRES_USER: system
      POSTGRES_PASSWORD: manager
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume_database:/var/lib/postgresql/data/pgdata

  quarkus-1:
    build:
      dockerfile: Dockerfile
    ports:
      - 9091:8081
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: manager
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/upsa
      QUARKUS_FLYWAY_CLEAN_AT_START: true
      QUARKUS_FLYWAY_MIGRATE_AT_START: true
      QUARKUS_SWAGGER_UI_ENABLE: true
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    depends_on:
      - database

volumes:
  volume_database: {}